### PR TITLE
Storemanagerui

### PR DESCRIPTION
**Pull request by zydplatform**
@armstrongsouljah @RLubwama @fahadmak @mwinel @WalujoEmmanuel @codjoero @oma0256 @sanya-kenneth @ruju256 @kaggwachristopher @bekeplar @habatkasa @amcodex

### CODE REVIEW

**Comment by zydplatform** [comment]
> @zydplatform can't get past your login page you may want to checkout your login form

@oma0256   my username for admin =>admin admin-password => admin
attendant username=>attendant ,attendant password =>attendant

**Comment by armstrongsouljah** [comment]
please add messages on your form informing the user that they have input wrong details.
prevent submission and not informing the user leaves them not knowing what to do next.
I suggest you add `span` tags to the form so that when i enter wrong in put you display an informative message using javascript.

**Comment by zydplatform** [comment]
> please add messages on your form informing the user that they have input wrong details.
> prevent submission and not informing the user leaves them not knowing what to do next.
> I suggest you add `span` tags to the form so that when i enter wrong in put you display an informative message using javascript.

@soultech thanks let me work on it

**Comment by armstrongsouljah** [comment]
@zydplatform my `git handle` is `armstrongsouljah` use that next time you make a PR

**Comment by armstrongsouljah** [comment]
You're not supposed to merge into master!

**Comment by WalujoEmmanuel** [comment]
@zydplatform You wouldn't have merged into master, you were ment to merge into the develop branch not master

**Comment by bekeplar** [comment]
please merging into master isn't acceptable.

**Pull request merged**
